set( BUILD_CUDA_STUBS       OFF CACHE BOOL "" FORCE )
set( BUILD_DOCS             OFF CACHE BOOL "" FORCE )
set( BUILD_EXAMPLES         OFF CACHE BOOL "" FORCE )
set( BUILD_JASPER           OFF CACHE BOOL "" FORCE )
set( BUILD_OPENEXR          OFF CACHE BOOL "" FORCE )
set( BUILD_SHARED_LIBS      OFF CACHE BOOL "" FORCE )
set( BUILD_PACKAGE          OFF CACHE BOOL "" FORCE )
set( BUILD_PERF_TESTS       OFF CACHE BOOL "" FORCE )
set( BUILD_TBB              OFF CACHE BOOL "" FORCE )
set( BUILD_TESTS            OFF CACHE BOOL "" FORCE )

set( BUILD_FAT_JAVA_LIB     OFF CACHE BOOL "" FORCE )

set( BUILD_WITH_DEBUG_INFO  OFF CACHE BOOL "" FORCE ) # enabled in CMakeLists.txt only for dev builds
set( BUILD_WITH_DYNAMIC_IPP OFF CACHE BOOL "" FORCE )
set( BUILD_WITH_STATIC_CRT  OFF CACHE BOOL "" FORCE )

set( BUILD_JPEG             ON  CACHE BOOL "" FORCE )
set( BUILD_PNG              ON  CACHE BOOL "" FORCE )
set( BUILD_TIFF             OFF CACHE BOOL "" FORCE )
if ( BUILD_ZLIB )
  set( BUILD_ZLIB ${BUILD_ZLIB} CACHE BOOL "" FORCE )
else()
  set( BUILD_ZLIB           OFF CACHE BOOL "" FORCE )
endif()

set( BUILD_opencv_apps           OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_calib3d        ON                         CACHE BOOL "" FORCE )
set( BUILD_opencv_core           ON                         CACHE BOOL "" FORCE )
set( BUILD_opencv_cudaarithm     OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudabgsegm     OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudacodec      OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudafeatures2d OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudafilters    OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudaimgproc    OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudalegacy     OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudaobjdetect  OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudaoptflow    OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudastereo     OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudawarping    OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_cudev          OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_hal            OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_highgui        OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_imgcodecs      ON                         CACHE BOOL "" FORCE )
set( BUILD_opencv_imgproc        ON                         CACHE BOOL "" FORCE )
set( BUILD_opencv_java           OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_objdetect      ON                         CACHE BOOL "" FORCE )
set( BUILD_opencv_ocl            OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_photo          OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_python2        OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_python3        OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_shape          OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_stitching      OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_superres       OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_ts             OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_video          OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_videoio        ON                         CACHE BOOL "" FORCE )
set( BUILD_opencv_videostab      OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_viz            OFF                        CACHE BOOL "" FORCE )
set( BUILD_opencv_world          OFF                        CACHE BOOL "" FORCE )

set( BUILD_opencv_features2d     ${BUILD_opencv_calib3d}    CACHE BOOL "" FORCE )
set( BUILD_opencv_flann          ${BUILD_opencv_features2d} CACHE BOOL "" FORCE )
set( BUILD_opencv_ml             ${BUILD_opencv_objdetect}  CACHE BOOL "" FORCE )

if ( MB_DESKTOP_BUILD )
  set( BUILD_opencv_highgui ON CACHE BOOL "" FORCE )
endif()

set( ENABLE_FAST_MATH          ON CACHE BOOL "" FORCE )
set( ENABLE_OMIT_FRAME_POINTER ON CACHE BOOL "" FORCE )

set( WITH_CAROTENE OFF CACHE BOOL "" FORCE )
set( WITH_CSTRIPES OFF CACHE BOOL "" FORCE )
set( WITH_CUDA     OFF CACHE BOOL "" FORCE )
set( WITH_CUFFT    OFF CACHE BOOL "" FORCE )
set( WITH_EIGEN    ON  CACHE BOOL "" FORCE )
set( WITH_MSMF     ON  CACHE BOOL "" FORCE )
set( WITH_JASPER   OFF CACHE BOOL "" FORCE )
set( WITH_LAPACK   OFF CACHE BOOL "" FORCE )
set( WITH_OPENEXR  OFF CACHE BOOL "" FORCE )
set( WITH_QT       OFF CACHE BOOL "" FORCE )
set( WITH_TIFF     OFF CACHE BOOL "" FORCE )
set( WITH_TBB      OFF CACHE BOOL "" FORCE )
set( WITH_WEBP     OFF CACHE BOOL "" FORCE )

set( WITH_1394          OFF CACHE BOOL "" FORCE )
set( WITH_FFMPEG        OFF CACHE BOOL "" FORCE )
set( WITH_GIGEAPI       OFF CACHE BOOL "" FORCE )
set( WITH_GPHOTO2       OFF CACHE BOOL "" FORCE )
set( WITH_GSTREAMER     ON  CACHE BOOL "" FORCE )
set( WITH_LIBV4L        ON  CACHE BOOL "" FORCE )
set( WITH_OPENCL        OFF CACHE BOOL "" FORCE )
set( WITH_OPENCLAMDBLAS OFF CACHE BOOL "" FORCE )
set( WITH_OPENCLAMDFFT  OFF CACHE BOOL "" FORCE )
set( WITH_PVAPI         OFF CACHE BOOL "" FORCE )
set( WITH_V4L           OFF CACHE BOOL "" FORCE )
set( WITH_VTK           OFF CACHE BOOL "" FORCE )
set( WITH_IPP           OFF CACHE BOOL "" FORCE )

# using FFMPEG fails to compile on ArchLinux
#if ( NOT APPLE ) # AVFoundation can read our test/bench MPGs
#  set( WITH_FFMPEG ON CACHE BOOL "" FORCE )
#endif()

if ( MB_QTGUI )
  set( WITH_QT ON CACHE BOOL "" FORCE )
endif()

if ( MB_TIFF )
  set( BUILD_TIFF ON CACHE BOOL "" FORCE )
  set( WITH_TIFF  ON CACHE BOOL "" FORCE )
endif()
