set( WITH_PTHREADS_PF ${MB_EMSCRIPTEN_ENABLE_PTHREADS} CACHE BOOL "" FORCE )
# Emscripten supports compiling SSE and SSE2 intrinsics to wasm SIMD (if enabled)
set( ENABLE_SSE  ${MB_EMSCRIPTEN_SIMD} CACHE BOOL "" FORCE )
set( ENABLE_SSE2 ${MB_EMSCRIPTEN_SIMD} CACHE BOOL "" FORCE )
set( ENABLE_SSE3 ${MB_EMSCRIPTEN_SIMD} CACHE BOOL "" FORCE )

include( "${CMAKE_CURRENT_LIST_DIR}/../common_options.cmake" )

set( WITH_LIBV4L    OFF CACHE BOOL "" FORCE )
set( WITH_MATLAB    OFF CACHE BOOL "" FORCE )
set( WITH_GTK       OFF CACHE BOOL "" FORCE )
set( WITH_GSTREAMER OFF CACHE BOOL "" FORCE )
