macro(subdirlist result curDir)
  file(GLOB children ${curDir}/*)
  set(dirlist "")
  foreach(child ${children})
    #MESSAGE(STATUS "Examining child: ${child}")
    if(IS_DIRECTORY ${child})
#        MESSAGE(STATUS "${child} is directory!")
        list(APPEND dirlist ${child})
    endif()
  endforeach()
  list(SORT dirlist)
  set(${result} ${dirlist})
endmacro()
